# Generated by Django 4.2.9 on 2024-02-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('contact_details', models.CharField(max_length=200)),
                ('insurance_information', models.CharField(max_length=200)),
                ('pre_existing_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('surgeries_or_treatments', models.TextField(blank=True)),
            ],
        ),
    ]
